"""move source title back to document chunks

Revision ID: 6c701064fbfe
Revises: ae3bf9908c22
Create Date: 2026-09-19 21:31:58.803383

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c701064fbfe"
down_revision: str | Sequence[str] | None = "ae3bf9908c22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_chunks", sa.Column("source_title", sa.Text(), nullable=True)
    )
    op.drop_column("documents", "source_title")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column(
            "source_title", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("document_chunks", "source_title")
    # ### end Alembic commands ###
