"""add document chunk embeddings

Revision ID: 9300538b4a23
Revises: dfcea771414b
Create Date: 2026-09-02 20:06:11.107087

"""

from collections.abc import Sequence

import pgvector.sqlalchemy.vector
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9300538b4a23"
down_revision: str | Sequence[str] | None = "dfcea771414b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_chunks",
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_chunks", "embedding")
    # ### end Alembic commands ###
