"""add source title to document chunks

Revision ID: 9b042e35f06a
Revises: 9300538b4a23
Create Date: 2026-09-19 14:40:54.940722

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b042e35f06a"
down_revision: str | Sequence[str] | None = "9300538b4a23"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_chunks", sa.Column("source_title", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_chunks", "source_title")
    # ### end Alembic commands ###
