"""move source title to documents

Revision ID: ae3bf9908c22
Revises: 9b042e35f06a
Create Date: 2026-09-19 15:48:36.676895

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae3bf9908c22"
down_revision: str | Sequence[str] | None = "9b042e35f06a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_chunks", "source_title")
    op.add_column(
        "documents", sa.Column("source_title", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "source_title")
    op.add_column(
        "document_chunks",
        sa.Column("source_title", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
